# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :ua_postgres do |t|
  end

  config.vm.hostname = "postgres"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4
  config.vm.provision :shell, :path => "setup/bootstrap.sh"
  
  # PostgreSQL Server port forwarding
  # config.vm.network :bridged
  config.vm.network :private_network, ip: "192.168.111.111"
  config.vm.network :forwarded_port, host: 5432, guest: 5432
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ua-postgres"
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "80"]  
  end
end

